# ------------------------------------------------------------------------ [ TEMPLATES ]

x-sdk-base: &sdk-base
  volumes:
    - ./shared-volume:/shared-volume

# build CONTEXT (only context here; no args to avoid override)
x-dotnet:  &dotnet  { context: ./dotnet }
x-elixir:  &elixir  { context: ./elixir }
x-go:      &go      { context: ./go }
x-java:    &java    { context: ./java }
x-node:    &node    { context: ./node }
x-php:     &php     { context: ./php }
x-python:  &python  { context: ./python }
x-rust:    &rust    { context: ./rust }
x-ruby:    &ruby    { context: ./ruby }

# Environment anchors for variants
x-env-core:   &env-core   { SDK_VARIANT: core }
x-env-legacy: &env-legacy { SDK_VARIANT: legacy }

# Build args
x-beta-val: &beta_val beta
x-rc-val:   &rc_val   rc
x-beta: &beta { args: { RELEASE_TAG: *beta_val } }
x-rc:   &rc   { args: { RELEASE_TAG: *rc_val } }

# ------------------------------------------------------------------------ [ SERVICES ]
services:

  scrapi:
    build: ./scrapi
    container_name: scrapi
    environment:
      EVAL_PROJ_SDK_KEY: ${EVAL_PROJ_SDK_KEY}
      BENCH_CLUSTER_SDK_KEY: ${BENCH_CLUSTER_SDK_KEY}
    image: scrapi:latest
    ports: ["8000:8000"]
    volumes: ["./shared-volume:/shared-volume"]

  docker-stats:
    build: ./docker-stats
    container_name: docker-stats
    image: docker-stats:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./shared-volume:/shared-volume

  # ------------------------------------------------------------------------ [ DOTNET ]
  dotnet-core:   { <<: *sdk-base, build: { <<: *dotnet }, environment: *env-core, container_name: dotnet-core }
  dotnet-legacy: { <<: *sdk-base, build: { <<: *dotnet }, environment: *env-legacy, container_name: dotnet-legacy }

  # ------------------------------------------------------------------------ [ ELIXIR ]
  elixir-core:   { <<: *sdk-base, build: { <<: *elixir }, environment: *env-core, container_name: elixir-core }

  # ------------------------------------------------------------------------ [ GO ]
  go-core:       { <<: *sdk-base, build: { <<: *go },     environment: *env-core, container_name: go-core }
  go-legacy:     { <<: *sdk-base, build: { <<: *go },     environment: *env-legacy, container_name: go-legacy }

  # ------------------------------------------------------------------------ [ JAVA ]
  java-core-rc:    { <<: *sdk-base, build: { <<: [*java, *rc] },   environment: *env-core, container_name: java-core-rc }
  java-core-beta:  { <<: *sdk-base, build: { <<: [*java, *beta] },   environment: *env-core, container_name: java-core-beta }
  java-legacy:     { <<: *sdk-base, build: { <<: *java },   environment: *env-legacy, container_name: java-legacy }

  # ------------------------------------------------------------------------ [ NODE ]
  node-core-beta: { <<: *sdk-base, build: { <<: [*node, *beta] }, environment: *env-core, container_name: node-core-beta }
  node-core-rc:  { <<: *sdk-base, build: { <<: [*node, *rc] },   environment: *env-core, container_name: node-core-rc }
  node-legacy:   { <<: *sdk-base, build: { <<: *node }, environment: *env-legacy, container_name: node-legacy }

  # ------------------------------------------------------------------------ [ PHP ]
  php-core:      { <<: *sdk-base, build: { <<: *php },    environment: *env-core, container_name: php-core }
  php-legacy:    { <<: *sdk-base, build: { <<: *php },    environment: *env-legacy, container_name: php-legacy }

  # ------------------------------------------------------------------------ [ PYTHON ]
  python-core-beta:   { <<: *sdk-base, build: { <<: [*python, *beta] }, environment: *env-core, container_name: python-core-beta }
  python-core-rc:   { <<: *sdk-base, build: { <<: [*python, *rc] }, environment: *env-core, container_name: python-core-rc }
  python-legacy: { <<: *sdk-base, build: { <<: *python }, environment: *env-legacy, container_name: python-legacy }

  # ------------------------------------------------------------------------ [ RUST ]
  rust-core:     { <<: *sdk-base, build: { <<: *rust },   environment: *env-core, container_name: rust-core }
  rust-legacy:   { <<: *sdk-base, build: { <<: *rust },   environment: *env-legacy, container_name: rust-legacy }

  # ------------------------------------------------------------------------ [ RUBY ]
  # ruby-core:     { <<: *sdk-base, build: { <<: *ruby },   environment: *env-core, container_name: ruby-core }
  ruby-legacy:   { <<: *sdk-base, build: { <<: *ruby },   environment: *env-legacy, container_name: ruby-legacy }