# ------------------------------------------------------------------------ [ TEMPLATES ]

x-sdk-base: &sdk-base
  volumes:
    - ./shared-volume:/shared-volume

x-dotnet: &dotnet   { build: ./dotnet }
x-elixir: &elixir   { build: ./elixir }
x-go:     &go       { build: ./go    }
x-java:   &java     { build: ./java  }
x-node:   &node     { build: ./node  }
x-php:    &php      { build: ./php   }
x-python: &python   { build: ./python}
x-rust:   &rust     { build: ./rust  }
x-ruby:   &ruby     { build: ./ruby  }

# Environment anchors for variants TODO: rc in the future
x-env-core:   &env-core   { SDK_VARIANT: core }
x-env-legacy: &env-legacy { SDK_VARIANT: legacy }

# ------------------------------------------------------------------------ [ SERVICES ]
services:

  scrapi:
    build: ./scrapi
    container_name: scrapi
    environment:
      EVAL_PROJ_SDK_KEY: ${EVAL_PROJ_SDK_KEY}
      BENCH_CLUSTER_SDK_KEY: ${BENCH_CLUSTER_SDK_KEY}
    image: scrapi:latest
    ports: ["8000:8000"]
    volumes: ["./shared-volume:/shared-volume"]

  docker-stats:
    build: ./docker-stats
    container_name: docker-stats
    image: docker-stats:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./shared-volume:/shared-volume

  # ------------------------------------------------------------------------ [ DOTNET ]
  dotnet-core:   { <<: [*sdk-base, *dotnet], environment: *env-core, container_name: dotnet-core }
  dotnet-legacy: { <<: [*sdk-base, *dotnet], environment: *env-legacy, container_name: dotnet-legacy }

  # ------------------------------------------------------------------------ [ ELIXIR ]
  elixir-core:   { <<: [*sdk-base, *elixir], environment: *env-core, container_name: elixir-core }

  # ------------------------------------------------------------------------ [ GO ]
  go-core:       { <<: [*sdk-base, *go],     environment: *env-core, container_name: go-core }
  go-legacy:     { <<: [*sdk-base, *go],     environment: *env-legacy, container_name: go-legacy }

  # ------------------------------------------------------------------------ [ JAVA ]
  java-core:     { <<: [*sdk-base, *java],   environment: *env-core, container_name: java-core }
  java-legacy:   { <<: [*sdk-base, *java],   environment: *env-legacy, container_name: java-legacy }

  # ------------------------------------------------------------------------ [ NODE ]
  node-core:     { <<: [*sdk-base, *node],   environment: *env-core, container_name: node-core }
  node-legacy:   { <<: [*sdk-base, *node],   environment: *env-legacy, container_name: node-legacy }

  # ------------------------------------------------------------------------ [ PHP ]
  php-core:      { <<: [*sdk-base, *php],    environment: *env-core, container_name: php-core }
  php-legacy:    { <<: [*sdk-base, *php],    environment: *env-legacy, container_name: php-legacy }

  # ------------------------------------------------------------------------ [ PYTHON ]
  python-core:   { <<: [*sdk-base, *python], environment: *env-core, container_name: python-core }
  python-legacy: { <<: [*sdk-base, *python], environment: *env-legacy, container_name: python-legacy }

  # ------------------------------------------------------------------------ [ RUST ]
  rust-core:     { <<: [*sdk-base, *rust],   environment: *env-core }
  rust-legacy:   { <<: [*sdk-base, *rust],   environment: *env-legacy, container_name: rust-legacy }

  # ------------------------------------------------------------------------ [ RUBY ]
  # ruby-core:     { <<: [*sdk-base, *ruby],   environment: *env-core, container_name: ruby-core }
  ruby-legacy:   { <<: [*sdk-base, *ruby],   environment: *env-legacy, container_name: ruby-legacy }
