name: Create Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

env:
  # GH Octokit (Kong App)
  GH_APP_ID: '229901'
  GH_APP_INSTALLATION_ID: '36921303'
  GH_APP_PRIVATE_KEY: ${{ secrets.KONG_APP_KEY_V2 }}

jobs:
  create-release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/releases/') || startsWith(github.ref, 'refs/heads/betas/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: pnpm/action-setup@v4
        with:
          version: 7.32.4

      - name: Install CLI(Tore) Dependencies
        run: pnpm install --dir cli

      - name: Create GitHub Release
        run: ./tore gh-create-release private-statsig-server-core
