name: Cut Release Candidate

on:
  workflow_dispatch:
  schedule:
    - cron: '0 13 * * 1'

env:
  # GH Octokit (Kong App)
  GH_APP_ID: '229901'
  GH_APP_INSTALLATION_ID: '36921303'
  GH_APP_PRIVATE_KEY: ${{ secrets.KONG_APP_KEY_V2 }}

jobs:
  release_candidate:
    if: github.event.repository.private
    timeout-minutes: 20
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
    
      - uses: pnpm/action-setup@v4
        with:
          version: 7.32.4
      
      - name: Config user
        run: |
          git config user.name "Xin Li (Bot)"
          git config user.email ${{ secrets.XIN_GH_EMAIL }}

 
      - name: Install CLI Dependencies
        run: pnpm install --dir cli
    
      - name: Sync stable with main branch
        run: |
            git fetch origin stable
            git fetch origin main
            git checkout stable 
            # TODO(xinli): Add some validation to check merge conflicts are always 
            git rebase origin/main -X theirs
            git push --force

      - name: Bump Version
        id: bump_version
        run: git checkout stable &&
            ./tore bump-version --create-branch --rc

      - name: Create Release
        run: ./tore gh-create-release private-statsig-server-core

      - name: Merge Back to Main
        run: ./tore merge-to-main

      - name: Print version number
        run: echo "Branch is ${{ steps.bump_version.outputs.version_branch }}"

      - name: Merge Version Bump Changes to Stable
        run: 
            git fetch origin stable
            git checkout stable 
            git fetch origin ${{ steps.bump_version.outputs.version_branch }}
            git merge origin/${{ steps.bump_version.outputs.version_branch }}
            git push