name: Main

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:

  release:
    types: [released, prereleased]

concurrency:
  group: main-${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  # -------------------------------------------------------------------- [Plan]

  lint:
    uses: ./.github/workflows/lint.yml

  build:
    needs: lint
    uses: ./.github/workflows/build.yml
    secrets: inherit

  package-verification:
    needs: lint
    uses: ./.github/workflows/package_verification.yml
    secrets: inherit

  tests:
    needs: lint
    uses: ./.github/workflows/statsig-tests.yml
    secrets: inherit

  kong:
    needs: lint
    uses: ./.github/workflows/kong_main.yml
    secrets: inherit