name: Package Verification

on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always
  FORCE_COLOR: true
  STATSIG_SERVER_SDK_KEY: ${{ secrets.KONG_SERVER_SDK_KEY }}

jobs:
  docker-based-verification:
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        config:
          - package: java
            tag: amazoncorretto_21_alpine_jdk

          - package: java
            tag: amazonlinux_2023

          - package: java
            tag: amazonlinux_2

          - package: python
            tag: ubuntu_noble

          - package: python
            tag: py_3_10_slim

          - package: python
            tag: py_3_10_alpine

          - package: node
            tag: node_20_slim

          - package: node
            tag: node_20_alpine

          - package: php
            tag: php_7_cli

          # todo: PHP musl support
          # - package: php
          #   tag: php_7_alpine

          - package: php
            tag: debian_11_slim

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - uses: pnpm/action-setup@v4
        with:
          version: 7.32.4

      - name: Install NPM Dependencies
        run: pnpm install --dir cli

      - name: Run Verification
        run: ./tore verify-package --package ${{ matrix.config.package }} --image-tag ${{ matrix.config.tag }} 


  node-package-verification:
    strategy:
      fail-fast: false
      matrix:
        runner:
          - windows-latest
          - ubuntu-latest
        tag:
          - beta
          - latest # prod

    timeout-minutes: 10
    runs-on: ${{ matrix.runner }}

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 7.32.4

      - name: Run Verification
        working-directory: examples/node/verify-package
        run: |
          pnpm init
          pnpm install @statsig/statsig-node-core@${{ matrix.tag }} typescript tsx @types/node
          pnpm exec tsx verify.ts

  python-package-verification:
    strategy:
      fail-fast: false
      matrix:
        runner:
          - windows-latest
          - ubuntu-latest
        tag:
          - beta
          - prod

    timeout-minutes: 10
    runs-on: ${{ matrix.runner }}

    steps:
      - uses: actions/checkout@v4

      - name: Run Verification
        working-directory: examples/python/verify-package
        run: |
          pip3 install ${{ matrix.tag == 'beta' && '--pre' || '' }} --upgrade statsig_python_core
          pip3 install mypy types-requests
          mypy --package statsig_python_core
          python3 verify.py

  php-package-verification:
    strategy:
      fail-fast: false
      matrix:
        runner:
          # - windows-latest # Uncomment when windows is supported by PHP
          - ubuntu-latest
        tag:
          - beta
          - prod

    timeout-minutes: 10
    runs-on: ${{ matrix.runner }}

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: ffi
          ini-values: ffi.enable=1

      - name: Run Verification
        working-directory: examples/php/verify-package
        run: |
          composer require statsig/statsig-php-core:${{ matrix.tag == 'beta' && 'dev-main' || '@stable' }}
          composer install
          php verify.php

  dotnet-package-verification:
    strategy:
      fail-fast: false
      matrix:
        runner:
          - windows-latest
          - ubuntu-latest
        tag:
          - beta
          - prod

    timeout-minutes: 10
    runs-on: ${{ matrix.runner }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Pin Statsig package version
        working-directory: examples/dotnet/verify-package
        shell: bash
        run: |
          if [[ "${{ matrix.tag }}" == "beta" ]]; then
            dotnet add package Statsig.Dotnet --prerelease
          else
            dotnet add package Statsig.Dotnet            # prod = latest stable
          fi

      - name: Run example
        working-directory: examples/dotnet/verify-package
        shell: bash
        run: |
          dotnet restore dotnet.csproj --no-cache
          dotnet run --configuration Release 

  go-package-verification:
    strategy:
      fail-fast: false
      matrix:
        runner:
          - windows-latest
          - ubuntu-latest
          - macos-latest
        tag:
          - beta
          - prod

    timeout-minutes: 10
    runs-on: ${{ matrix.runner }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Go SDK
        uses: actions/setup-go@v3
        with: 
          go-version: 1.22

      - name: Update to latest SDK version
        working-directory: statsig-go/verify-package
        run: go get github.com/statsig-io/statsig-server-core/statsig-go@latest

      - name: Install Go SDK
        run: go install github.com/statsig-io/statsig-server-core/statsig-go/cmd/post-install@latest

      # macOS / Linux
      - name: Add Go Bin to Path and Run post-install CLI tool (macOS/Linux)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          # export PATH="$PATH:$(go env GOPATH)/bin"
          post_install_val=$(post-install)
          post_install_cmd=$(echo "$post_install_val" | tail -n 4 | head -n 1)
          echo "post_install_cmd is: $post_install_cmd"
          eval "$post_install_cmd"
          echo "STATSIG_LIB_DIR=$STATSIG_LIB_DIR" >> $GITHUB_ENV
          echo "CGO_ENABLED=$CGO_ENABLED" >> $GITHUB_ENV
          echo "CGO_CFLAGS=$CGO_CFLAGS" >> $GITHUB_ENV
          echo "CGO_LDFLAGS=$CGO_LDFLAGS" >> $GITHUB_ENV
          echo "DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH" >> $GITHUB_ENV

      # Windows
      - name: Add Go Bin to Path and Run post-install CLI tool (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          # $env:PATH += ";$env:USERPROFILE\.statsig\bin"
          # $env:PATH += ";$env:STATSIG_LIB_DIR"
          $post_install_cmd = (post-install | Select-Object -Last 4 | Select-Object -First 1)
          Write-Host "Post install output:`n$post_install_cmd"
          Invoke-Expression $post_install_cmd
          Add-Content -Path $env:GITHUB_ENV -Value "STATSIG_LIB_DIR=$env:STATSIG_LIB_DIR"
          Add-Content -Path $env:GITHUB_ENV -Value "CGO_ENABLED=$env:CGO_ENABLED"
          Add-Content -Path $env:GITHUB_ENV -Value "CGO_CFLAGS=$env:CGO_CFLAGS"
          Add-Content -Path $env:GITHUB_ENV -Value "CGO_LDFLAGS=$env:CGO_LDFLAGS"
          Add-Content -Path $env:GITHUB_ENV -Value "DYLD_LIBRARY_PATH=$env:DYLD_LIBRARY_PATH"
          Add-Content -Path $env:GITHUB_ENV -Value "LD_LIBRARY_PATH=$env:LD_LIBRARY_PATH"
          Add-Content -Path $env:GITHUB_ENV -Value "PATH=$env:PATH"
  

      - name: Run Small Go Program to Verify the SDK
        working-directory: statsig-go/verify-package
        run: |
          go mod tidy
          ls $STATSIG_LIB_DIR
          go run main.go
