name: Release Bot

on:
  pull_request:
    types: [opened, reopened, closed]
    branches: 
      - main
      - stable
      - rc
      - 'releases/**'
  release:
    types: [released, prereleased]

env:
  # GH Octokit (Kong App)
  GH_APP_ID: '229901'
  GH_APP_INSTALLATION_ID: '36921303'
  GH_APP_PRIVATE_KEY: ${{ secrets.KONG_APP_KEY_V2 }}

jobs:
  info:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Print Github
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "${{ github.event_name }}"
          echo $GITHUB_CONTEXT || true
          echo $GITHUB_CONTEXT > github_context.json

      - name: Print GitHub Event JSON
        run: |
          echo "-- Loading JSON from $GITHUB_EVENT_PATH --"
          cat $GITHUB_EVENT_PATH

      - name: Print Env
        run: printenv

  run-publish-action:
    if: contains(github.head_ref, 'betas/') || contains(github.head_ref, 'releases/')
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
            repo-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: pnpm/action-setup@v4
        with:
          version: 7.32.4

      - uses: statsig-io/statsig-publish-sdk-action@main
        with:
          kong-private-key: ${{ secrets.KONG_GH_APP_PRIVATE_KEY }}
