name: Scheduled SDK Benchmark

on:
  # push:
  workflow_dispatch:
  schedule:
    - cron: '*/60 * * * *'
  
env:
  PERF_SDK_KEY: ${{ secrets.PERF_SDK_KEY }}
  CAPTURE: python $GITHUB_WORKSPACE/.github/benchmark_capture.py

jobs:
  bench-cluster:
    runs-on: ubuntu-latest
    if: github.event.repository.private
    timeout-minutes: 30
    env:
      EVAL_PROJ_SDK_KEY: ${{ secrets.EVAL_PROJ_SDK_KEY }}
      BENCH_CLUSTER_SDK_KEY: ${{ secrets.BENCH_CLUSTER_SDK_KEY }}
    strategy:
      matrix:
        sdk-service:
          - dotnet-core
          - dotnet-legacy
          - elixir-core
          - go-core
          - go-legacy
          - java-core-beta
          - java-core-rc
          - java-legacy
          - node-core-beta
          - node-core-rc
          - node-legacy
          - php-core
          - php-legacy
          - python-core-beta
          - python-core-rc
          - python-legacy
          - ruby-legacy
          # - ruby-core
          - rust-core-beta
          - rust-core-rc
          - rust-legacy

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Bench Cluster
        run: |
          cd benchmarking/bench-cluster
          docker compose up --build scrapi docker-stats ${{ matrix.sdk-service }}
